# Arreglos y clases

## Matrices
es un arreglo de mxm elementos


\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1m} \\
a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mm}
\end{bmatrix}


In [1]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [19]:
#vamos a crear extra
B=[[21,34,40],[71,17,77],[73,81,28]]
print (A+B)
print (2*A)



[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
A[0][0]
[1,2,3]

[1, 2, 3]

In [10]:
## Vectores y listas
L=A[0]
M=B[0]
print(L)
print(M)

[1, 2, 3]
[21, 34, 40]


In [18]:
a=L[0]
b=M[0]
print(a+b)
a==1

22


True

In [12]:
a==1

True

### Suma de "vectores"


In [22]:
len(L)==len(M)

suma=[L[0] + M[0], L[1]+M[1], L[2]+M[2]]

print(suma)

suma=[L[i]+M[i] for i in range (3)]
suma

[22, 36, 43]


[22, 36, 43]

#### creacion de funciones globales

La funcion para crear funciones es `def` que se cierra con un debug(`print o return`)

In [24]:
def Hola():
  print("Hola, me llamo natalia")


In [25]:
Hola()

Hola, me llamo natalia


In [28]:
def saludar(s,n):
  print(f"Hola, me llano {s} y tengo {n} años")

In [29]:
saludar("natalia", 18)

Hola, me llano natalia y tengo 18 años


In [42]:
I = [i for i in range(10)]
def par(x):
  for x in range (10):
    if x%2==0:
      print(f"{x} es par")
    else:
      print(f"{x} es impar")

In [40]:
par(6)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [55]:
def suma_vectorial(L,M):
  x = [L[i]+M[i] for i in range(len(L))]
  return x

In [56]:
L=[1,2,3]
M=[21,34,40]
suma_vectorial(L,M)

[22, 36, 43]

### Modulos o librerias


In [57]:
import math
from math import sqrt,pi

In [58]:
sqrt(68)

8.246211251235321

In [59]:
pi

3.141592653589793

## el modulo Numpy

LAduncion  `array`

In [60]:
import numpy as np

L_vector = np.array(L)
M_vector = np.array(M)

L_vector + M_vector

array([22, 36, 43])

In [62]:
C = [9,2,2,2,3,3,2,17,2]
A = [8,1,1,1,2,2,1,16,1]

C_matriz = np.array(C).reshape(3,3)
A_matriz = np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [63]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])

In [64]:
A_matriz @C_matriz

array([[76, 36, 21],
       [17, 42, 12],
       [43, 67, 52]])